/* Selecting Album to Purchase */
--looking at tracks sold in USA
WITH usa_tracks AS(
     SELECT il.track_id AS track_id
       FROM customer AS c
       JOIN invoice AS i
         ON c.customer_id = i.customer_id 
       JOIN invoice_line AS il
         ON i.invoice_id = il.invoice_id 
      WHERE c.country LIKE 'USA';
)

--Number of tracks sold in USA by Genre 
 SELECT g.name AS genre, 
        COUNT(ts.track_id) AS num_track_sold,
		ROUND((CAST(COUNT(ts.track_id) AS FLOAT) / (SELECT COUNT(track_id)
		                                              FROM usa_tracks))*100, 2) AS percentage_sold
   FROM track AS t
   JOIN usa_tracks AS ts
     ON t.track_id = ts.track_id
   JOIN genre AS g
     ON t.genre_id = g.genre_id
  GROUP BY genre
  ORDER BY num_track_sold DESC;
  
/* Analyzing Employee Sales Performance */

--Finding total sales generated by employee
SELECT e.first_name || ' ' || e.last_name AS employee_name,
       SUBSTR(e.hire_date,1,10) AS hire_date,
       SUM(i.total) AS total_sales
  FROM customer AS c
  JOIN invoice AS i
    ON c.customer_id = i.customer_id
  JOIN employee AS e
    ON c.support_rep_id = e.employee_id
 GROUP BY employee_name;

/* Analyzing Sales by Country */

WITH country_or_other AS ( 
SELECT CASE WHEN (SELECT COUNT(*)
                    FROM customer
				   WHERE country = c.country) = 1 THEN 'Other'
			ELSE c.country
			 END AS country, 
       c.customer_id AS customer_id, 
       il.*
  FROM invoice AS i
  JOIN invoice_line AS il
    ON i.invoice_id = il.invoice_id
  JOIN customer AS c
    ON i.customer_id = c.customer_id
)

SELECT country,
       COUNT(DISTINCT customer_id) AS total_customers,
       SUM(unit_price * quantity) AS total_sales,
	   SUM(unit_price * quantity)/ COUNT(DISTINCT customer_id) AS customer_lifetime_value,
	   SUM(unit_price * quantity) / COUNT(DISTINCT invoice_id) AS average_order_value,
	   CASE WHEN country LIKE 'Other' THEN 1
	        ELSE 0
			END AS sort
  FROM country_or_other
 GROUP BY country
 ORDER BY sort, total_sales DESC

/* Albums vs Individual Tracks */

WITH invoice_first_track AS ( 
SELECT il.invoice_id AS invoice_id,
       MIN(il.track_id) AS first_track_id
  FROM invoice_line AS il
 GROUP BY invoice_id
)

SELECT album_purchase, 
       COUNT(invoice_id) AS total_invoices,
	   CAST(COUNT(invoice_id) AS FLOAT) / (SELECT COUNT(*)
	                                         FROM invoice) AS percent_of_invoices
  FROM (SELECT if.*,
               CASE WHEN (SELECT t.track_id 
			                FROM track AS t
						   WHERE t.album_id = (SELECT t2.album_id
						                         FROM track AS t2
												WHERE t2.track_id = if.first_track_id)
				EXCEPT
				
				SELECT il2.track_id
				  FROM invoice_line AS il2
				 WHERE il2.invoice_id = if.invoice_id) IS NULL
				AND
			    (SELECT il2.track_id 
				   FROM invoice_line AS il2
				  WHERE il2.invoice_id = if.invoice_id
				  
				  EXCEPT
				  
				  SELECT t.track_id
				    FROM track AS t
				   WhERE t.album_id = (SELECT t2.album_id
				                         FROM track t2
										WHERE t2.track_id = if.first_track_id)) IS NULL
				  THEN 'yes'
				  ELSE 'No'
				  END AS 'album_purchase'
				 FROM invoice_first_track AS if)
				GROUP BY album_purchase;
			     	
	   